name: anaconda-client-env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - fenics
  - matplotlib
  - numpy
  - scipy
  - pytest==6.2.5
  - pytest-cov==2.10.1
  - pytest-xdist==2.5.0
  - sphinx
  - jupyter-book
  - jupyter-sphinx
