name: anaconda-client-env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python==3.8.12
  - fenics==2019.1.0
  - matplotlib==3.5.1
  - numpy==1.22.2
  - scipy==1.8.0
  - mshr==2019.1.0
  - pip==23.0
  - pandas==1.5.3
  - pytest==6.2.5
  - pytest-cov==2.10.1
  - pytest-xdist==2.5.0
  - sphinx
  - jupyter-book
  - jupyter-sphinx
