name: psf
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - fenics
  - matplotlib
  - numpy
  - scipy
  - pandas
  - mshr
  - ipykernel
  - slim
  - bioconda::snakemake
  - hyperopt 
  - pyslim>=1.0.1  
