name: psf
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python
  - fenics
  - matplotlib
  - numpy
  - scipy
  - pandas
  - mshr
  - ipykernel
  - pyslim>=1.0.1
  - slim
  - snakemake
  - hyperopt   
