name: Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.8]
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Conda
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: anaconda-client-env
          environment-file: requirements/ci-environment.yml
          cache-env: true
          extra-specs: |
            python=${{ matrix.python }}

      - name: Run tests
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list
          python3 -m pytest -xv -n2 --cov=product_fem --cov-report=xml --cov-branch tests

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3

      # - name: Build docs
      #   shell: bash -l {0}
      #   run: |
      #     micromamba info
      #     micromamba list
      #     cd docs
      #     PYTHONPATH=".." make
